AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
  Exclude:
    - vendor/**/*

AlignParameters:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Max: 200
MethodLength:
  Max: 30
StringLiterals:
  Enabled: false
